# Site settings
title: Meetings avec AA
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  2 chaises. 1 artiste. 1 animatrice. Andrée-Anne Brunet met en lumière le parcours
  original d'un artiste vivant une réalité bien différente de la nôtre.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: aabrunetnrj
timezone: America/Montreal

# Build settings
markdown: kramdown
