---
title: Meetings avec AA
email: your-email@domain.com
description: |
  2 chaises. 1 artiste. 1 animatrice. Andrée-Anne Brunet met en lumière le parcours original d'un artiste vivant une réalité bien différente de la nôtre.
baseurl: ''
url: http://meetingsavecaa.com
twitter_username: aabrunetnrj
timezone: America/Montreal
markdown: kramdown
